name: Publish to Crates.io

# This workflow runs automatically when you push a new git tag that starts with 'v'
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # Get the source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache dependencies to speed up future runs
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # The actual publish step
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
